### ISSUE TITLE
SecurityFilterMiddleware: Fallbacking to AnonymousProfile using OIDC?

### ISSUE THREAD

**Issue by windymelt** [pac4j/http4s-pac4j#22]
Hi, I have questions about OidcClient and AnonymousClient.
Can we use `SecurityFilterMiddleware` to configure endpoints like the following?

- Create a Profile based on that information if already logged in with OIDC
- If not, create an `AnonymousProfile` without redirecting to the OIDC authentication screen

I have tried this with authorizer and other settings, but have not been successful. It always fails to authenticate or always redirects.

My purpose is defining GraphQL endpoint with authorization. Though some of query needs authorization, endpoint itself requires no authorization. it just needs OIDC / Anonymous profile (I don't need redirect). 

Thank you.

**Comment by windymelt** [comment]
Currently, I manually retrieving profile like this (This method requires no AnonymousClient) but not intuitive.

```scala
  def graphqlRoutes(graphQL: GraphQL): HttpRoutes[IO] = Session
    .sessionManagement[IO](sessionConfig)
    .apply {
      HttpRoutes.of[IO] {
        case req @ POST -> Root / "graphql" =>
          val ctx = contextBuilder(req, conf)
          val manager = new ProfileManager(ctx, conf.getSessionStore())
          val profile = manager.getProfile
          val profileOpt = Option.unless(profile.isEmpty())(profile.get())

          val modelUser: Option[model.User] =
            profileOpt.map(/* model convert method */)
          req
            .as[Json]
            .flatMap(j => graphQL.query(j, modelUser))
            .flatMap {
              case Right(json) => Ok(json)
              case Left(json)  => BadRequest(json)
            }
      }
    }
```

I think making `Middleware` just retrieving profiles may help.

**Comment by leleuj** [comment]
For questions, please use https://stackoverflow.com with the pac4j tag

**Comment by windymelt** [comment]
Thank you for redirecting! I posted to stackoverflow: https://stackoverflow.com/questions/76051490/pac4j-securityfiltermiddleware-fallbacking-to-anonymousprofile-using-oidc
