### ISSUE TITLE
pac4jCsrfToken is misusing the recommended “SameSite“ attribute

### ISSUE THREAD

**Issue by KayleeTheMech** [pac4j/http4s-pac4j#27]
Hey so,
   i have a warning in my browser that will probably mean that they way this package uses cookies won't work forever. 

"Cookie “pac4jCsrfToken” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite "

I assume this is because I'm using this package to deliver authentication and authorization for a http4s scala backend with two react single page application frontends accessing that backend.

**Comment by leleuj** [comment]
You need to define the `SameSite` attribute cookie for the CSRF protection in pac4j. By default, it is not defined.
