### ISSUE TITLE
Improve handling for various cookie options

### ISSUE THREAD

**Issue by nigredo-tori** [pac4j/http4s-pac4j#4]
The current implementation discards data when converting Pac4J `Cookie` type to `ResponseCookie` [here](https://github.com/pac4j/http4s-pac4j/blob/543e8fb5ed15ad877eb0b135f9e46e1f39d6cdaf/src/main/scala/org/pac4j/http4s/Http4sWebContext.scala#L153). Note that `HttpOnly` and `Secure` are ignored. These are important, and we can easily map them to `ResponseCookie`. It also wouldn't hurt to properly handle the other cookie options.

Additionally, `Http4sCacheSessionStore` always creates session ID cookies [with default flags](https://github.com/pac4j/http4s-pac4j/blob/f4e0404c296fdac280212c9b7c794f85908e9566/src/main/scala/org/pac4j/http4s/Http4sCacheSessionStore.scala#L43). I'd like an option to configure these. In particular, making the session ID `HttpOnly` and/or `Secure` seems reasonable.

**Comment by leleuj** [comment]
Sure. It makes sense. Please submit a PR for that? Thx
