### ISSUE TITLE
Discussion: Integrating with SPAs and saving user to the DB on callback?

### ISSUE THREAD

**Issue by KaranAhlawat** [pac4j/http4s-pac4j#40]
Hello,
I've been implementing OIDC, OAuth and Form Client for my application. While pac4j makes it very easy in the server based scenario, I still have a few confusions around integrating with SPAs. Are there any go-to guides/articles/advice in this area? Any sample code I could look at (doesn't have to be in Http4s, I can probably port between frameworks).

Also, I'm trying to save the returned user from OIDC to the database.
1. Is this even a good idea? I need a user in the db for the business logic part of my app.
2. How would I go about doing this? By the time the callback logic is finished, the user profile is not there, hence I cannot make a call to save the user to the DB.

I'd really appreciate any help and advice in these areas, thank you

**Comment by froth** [comment]
Hi @KaranAhlawat ,

I am currently on Christmas holiday and don't have a computer with me. So my answers come from memory.

 For the SPA part:
You have to wrap your APIs with `SecurityFilterMiddleware.securityFilter`. For the login part I am unsure of an optimal implementation but we implemented it by a separate page which is also protected by securityFilter and redirect back to the SPA after login. However we use only a single OICD provider and no Form login, as it is an internal backoffice application. I don't know how to implement this with a 'real' SPA without a separate login page. But that's just my knowlede. It could totally be possible, it just was not necessary for my use case so I did not try very hard. 

For the database part:

I think this is a valid way of doing things. You can use `Http4sGenericSessionStore` and implement `CacheSessionRepository` with the database system of your choice. This however means you need a way to store a `Map[String, AnyRef]`. I implemented this in a generic way using Java Serialization and special cased the values I needed access to in my business logic. (At least that's the way I remember doing it).

I hope this helps. If not I can look up what I did exactly after Christmas.

**Comment by karan-hsc** [comment]
For the second part, this is what I ended up with

```scala
      if key === "pac4jUserProfiles" then
        val profileMap = value.asInstanceOf[java.util.LinkedHashMap[String, UserProfile]]
        if profileMap.containsKey("GoogleOidcClient") then
          val profile = profileMap.get("GoogleOidcClient").asInstanceOf[GoogleOidcProfile]
          userRepo
            .insertUser(
              User(
                id = UserID(""),
                username = Username(profile.getDisplayName),
                email = Email(profile.getEmail).map(UserEmail.apply).toOption,
                password = None
              )
            )
            .void
        else if profileMap.containsKey("GitHubClient") then
          val profile = profileMap.get("GitHubClient").asInstanceOf[GitHubProfile]
          userRepo
            .insertUser(
              User(id = UserID(""), username = Username(profile.getDisplayName), email = None, password = None)
            )
            .void
        else IO.unit
      else IO.unit
```

Not sure if I'm too happy with it, but it does save to the DB.

Also, the part with the SPA i'm struggling with is, how do I tell on the client that I am in fact logged in correctly and authenticated. I don't think I can rely on the session cookie being present, as that can be established by other means. Maybe during the re-direct, I can provide some query param to tell the application I'm authenticated?

**Comment by KaranAhlawat** [comment]
For the second part, this is what I ended up with

```scala
      if key === "pac4jUserProfiles" then
        val profileMap = value.asInstanceOf[java.util.LinkedHashMap[String, UserProfile]]
        if profileMap.containsKey("GoogleOidcClient") then
          val profile = profileMap.get("GoogleOidcClient").asInstanceOf[GoogleOidcProfile]
          userRepo
            .insertUser(
              User(
                id = UserID(""),
                username = Username(profile.getDisplayName),
                email = Email(profile.getEmail).map(UserEmail.apply).toOption,
                password = None
              )
            )
            .void
        else if profileMap.containsKey("GitHubClient") then
          val profile = profileMap.get("GitHubClient").asInstanceOf[GitHubProfile]
          userRepo
            .insertUser(
              User(id = UserID(""), username = Username(profile.getDisplayName), email = None, password = None)
            )
            .void
        else IO.unit
      else IO.unit
```
Not sure if I'm too happy with it, but it does save to the DB.

Also, the part with the SPA i'm struggling with is, how do I tell on the client that I am in fact logged in correctly and authenticated. I don't think I can rely on the session cookie being present, as that can be established by other means. Maybe during the re-direct, I can provide some query param to tell the application I'm authenticated?

**Comment by KaranAhlawat** [comment]
I have found another approach which I frankly like better, creating a custom profile manager that saves to the DB
```scala
case class DbProfileManager(
  dispatcher: Dispatcher[IO],
  webcontext: WebContext,
  store: SessionStore,
  userRepo: UserRepository
) extends ProfileManager(webcontext, store):
  override def save(saveInSession: Boolean, profile: UserProfile, multiProfile: Boolean): Unit =
    val saveToDbIO = profile.getClientName match
      case "FormClient"       => IO.unit
      case "GoogleOidcClient" =>
        val gp   = profile.asInstanceOf[GoogleOidcProfile]
        val user = User(
          id = UserID(""),
          username = Username(gp.getDisplayName),
          email = Email(gp.getEmail).map(UserEmail.apply).toOption,
          password = None
        )
        userRepo.insertUser(user).void
      case "GitHubClient"     =>
        val gp   = profile.asInstanceOf[GitHubProfile]
        val user = User(id = UserID(""), username = Username(gp.getDisplayName), email = None, password = None)
        userRepo.insertUser(user).void

    val _ = Try(dispatcher.unsafeRunSync(saveToDbIO))

    super.save(saveInSession, profile, multiProfile)
```

The only thing I'm kinda worried about is the unsafe run sync call hits the DB directly, and I'm not sure if that might become a problem, blocking a JVM thread

**Comment by froth** [comment]
> Also, the part with the SPA i'm struggling with is, how do I tell on the client that I am in fact logged in correctly and authenticated. I don't think I can rely on the session cookie being present, as that can be established by other means. Maybe during the re-direct, I can provide some query param to tell the application I'm authenticated?

What I did is an API behind pac4j that returns the login information. Then I call that from inside a react spa and act on that. But I think it might be  possible to get additional query parameters in pac4j. I think a good starting point to have a look would be DefaultCallbackLogic.

**Comment by froth** [comment]
> The only thing I'm kinda worried about is the unsafe run sync call hits the DB directly, and I'm not sure if that might become a problem, blocking a JVM thread

As long as you(or your DB client) uses `IO.blocking` correctly, dispatcher works fine, nothing special to worry about. For more detail the Dispatcher [https://typelevel.org/cats-effect/docs/std/dispatcher](documentation) is very good.

**Comment by KaranAhlawat** [comment]
Thanks! I'm using Skunk, and it's non-blocking down to the network, so I should be good on that front. I also  read the docs, good to find out I can instantiate a Dispatcher wherever needed, threading it around was getting a bit out of hand.

As for the API for the SPA, is the source possibly somewhere public I could look at? I'm interested in *what* you were returning for the login information.

Cheers, and happy holidays :smile:

**Comment by froth** [comment]
> Thanks! I'm using Skunk, and it's non-blocking down to the network, so I should be good on that front. I also  read the docs, good to find out I can instantiate a Dispatcher wherever needed, threading it around was getting a bit out of hand.
> 
> As for the API for the SPA, is the source possibly somewhere public I could look at? I'm interested in *what* you were returning for the login information.
> 
> Cheers, and happy holidays :smile: 

Unfortunately it is $WORK and not open source.  But I believe that it returns something like  `{"username":"froth"}` which I then use to display the username in the right upper corner. And if the API returns 403(?) I know that they are not logged in.

**Comment by KaranAhlawat** [comment]
Thanks, I'll try that out
