### ISSUE TITLE
Support for 2.13.3?

### ISSUE THREAD

**Issue by rparree** [pac4j/http4s-pac4j#6]
Hi,

I am looking for a solution to authenticate requests to keycloak. However we're using Scala 2.13.3. Are you considering supporting that?

tx,

**Comment by rparree** [comment]
Awesome, this is really great! Thanks

**Comment by leleuj** [comment]
Should I cut a v1.01 release?

**Comment by rparree** [comment]
I'll be adding keycloak later this week to a project i am migrated from akka-http to http4s. If you can make a version available on maven central that has bee cross-compiled, than that would be great.

**Comment by leleuj** [comment]
OK. It's in progress. It will show up on the Maven central repository within a few hours...
